<Project>

	<Import Project="Sachssoft.Sasogine.Package.props" />

	<PropertyGroup>
		<!-- General -->
		<RootNamespace>Sachssoft.Sasogine.UI</RootNamespace>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<!-- AOT / Trimming -->
		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible>true</IsAotCompatible>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>

		<!-- Documentation -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<!-- NuGet Metadata -->
		<Description>
			UI components and controls for the Sasogine game engine.
		</Description>

		<PackageReleaseNotes>
			Sasogine UI Alpha release.
		</PackageReleaseNotes>

		<PackageTags>
			Sasogine;UI;UserInterface;Controls;MonoGame;GameEngine;Framework;AOT;Trimming
		</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Sachssoft.Sasogine.DesktopGL"
						  Version="$(VersionPrefix)-$(VersionSuffix)" />
	</ItemGroup>

</Project>