<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<!--<RootNamespace>Sachssoft.Sasogine</RootNamespace>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>-->
		<Title>Sasogine</Title>
		<Copyright>© Tobias Sachs (Sachssoft)</Copyright>
	</PropertyGroup>

	<PropertyGroup>
		<IsTestProject>false</IsTestProject>
		<BuildProjectReferences>false</BuildProjectReferences>
		<BuildProject>false</BuildProject>
		<DisableBuild>true</DisableBuild>
	</PropertyGroup>

	<Target Name="Build" Condition="'$(DisableBuild)' == 'true'">
	</Target>
	
	<ItemGroup>
	  <Folder Include="Projects\Basic\Graphics\Tiles\" />
	  <Folder Include="Projects\Toolkit\Shaders\" />
	  <Folder Include="Projects\Toolkit\Tools\ObjectInsertTool\" />
	</ItemGroup>
</Project>