<Project>

	<Import Project="Sachssoft.Sasogine.Package.props" />

	<PropertyGroup>
		<!-- General -->
		<RootNamespace>Sachssoft.Sasogine.Extensions.Sasodoc</RootNamespace>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<!-- AOT / Trimming -->
		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible>true</IsAotCompatible>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>

		<!-- Documentation -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<!-- NuGet Metadata -->
		<Description>
			Sasodoc extensions for Sasogine based on MonoGame DesktopGL.
		</Description>

		<PackageReleaseNotes>
			Sasodoc Extensions Alpha release for Sasogine.
		</PackageReleaseNotes>

		<PackageTags>
			Sasogine;Sasodoc;MonoGame;GameEngine;Framework;AOT;Trimming
		</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Sachssoft.Sasodoc"
						  Version="1.0.0" />

		<PackageReference Include="Sachssoft.Sasogine.DesktopGL"
						  Version="$(VersionPrefix)-$(VersionSuffix)" />
	</ItemGroup>

</Project>