<Project>

	<Import Project="Sachssoft.Sasogine.Package.props" />

	<PropertyGroup>
		<!-- General -->
		<RootNamespace>Sachssoft.Sasogine.Documents</RootNamespace>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<!-- AOT / Trimming -->
		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible>true</IsAotCompatible>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>

		<!-- Documentation -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<!-- NuGet Metadata -->
		<Description>
			Document and serialization support for the Sasogine game engine, including structured document handling and resource loading.
		</Description>

		<PackageReleaseNotes>
			Introduces the Sasogine document and serialization infrastructure.
		</PackageReleaseNotes>

		<PackageTags>
			Sasogine;Documents;Serialization;Resources;XML;JSON;Binary;FrameSet;TextureAtlas;MonoGame;GameEngine;Framework;AOT;Trimming
		</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Sachssoft.Sasogine.DesktopGL"
						  Version="$(VersionPrefix)-$(VersionSuffix)" />
		<PackageReference Include="Sachssoft.Sasodoc"
						  Version="1.0.0" />
		<PackageReference Include="Sachssoft.Sasodoc.Json"
						  Version="1.0.0" />
	</ItemGroup>

</Project>