<Project>

	<PropertyGroup>
		<!-- General -->
		<TargetFrameworks>net8.0;net9.0;net10.0;</TargetFrameworks>
		<RootNamespace>Sachssoft.Sasogine</RootNamespace>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<!-- AOT / Trimming -->
		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible>true</IsAotCompatible>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>

		<!-- Documentation -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Sachssoft.Sasogine.DesktopGL"
						  Version="$(VersionPrefix)-$(VersionSuffix)" />
	</ItemGroup>

</Project>