<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0;</TargetFrameworks>
		<PackageOutputPath>..\..\..\Packages</PackageOutputPath>
		<Nullable>enable</Nullable>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>

		<PackageId>Sachssoft.Sasogine.UI.DesktopGL</PackageId>
		<Title>Sasogine DesktopGL</Title>
		<Description>
			Sasogine DesktopGL backend based on MonoGame.
		</Description>

		<PackageTags>
			MonoGame;Sasogine;GameEngine;DesktopGL;OpenGL
		</PackageTags>
	</PropertyGroup>

	<Import Project="..\..\..\Sachssoft.Sasogine.UI.props" />

	<PropertyGroup>
		<DefineConstants>
			$(DefineConstants);
			BACKEND_GL;
			DEVICE_DESKTOP
		</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\..\..\Projects\UI\**\*.cs">
			<LinkBase>UI</LinkBase>
		</Compile>
	</ItemGroup>
	
	<ItemGroup>
		<None Include="..\..\..\README.md" Pack="true" PackagePath="/" />
		<None Include="..\..\..\LICENSE.md" Pack="true" PackagePath="/" />
	</ItemGroup>

</Project>