name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "BUG: "
labels:
  - bug
assignees:
  - Sachssoft

body:
  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      placeholder: "Describe the bug and what happened."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "🔁 Steps to reproduce"
      placeholder: "Describe the steps to reproduce the bug."

  - type: textarea
    id: expected
    attributes:
      label: "✅ Expected behavior"
      placeholder: "What should happen instead?"

  - type: textarea
    id: screenshot
    attributes:
      label: "📷 Screenshot"
      placeholder: "Drag and drop a screenshot here."

  - type: textarea
    id: additional
    attributes:
      label: "📎 Additional information"
      placeholder: "Add logs, error messages, or other details."
