name: 🚀 Feature Request
description: Suggest a new feature
title: "FEATURE: "
labels:
  - enhancement
assignees:
  - Sachssoft

body:
  - type: input
    id: description
    attributes:
      label: "📝 Description"
      placeholder: "What should this feature do?"
    validations:
      required: true
