name: 🚀 Feature Request
description: Suggest a new feature
title: "FEATURE: "
labels:
  - feature
assignees:
  - Sachssoft

body:
  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      placeholder: "Describe the feature and what it should do."
    validations:
      required: true
