name: ❓ Question
description: Ask a question
title: "QUESTION: "
labels:
  - question
assignees:
  - Sachssoft

body:
  - type: textarea
    id: question
    attributes:
      label: "❓ Question"
      placeholder: "Describe your question."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "📄 Context"
      placeholder: "Add any relevant context, code, or examples."
