name: 📌 Task
description: Create a task, refactor, improvement, or change
title: "TASK: "
labels:
  - task
assignees:
  - Sachssoft

body:
  - type: dropdown
    id: type
    attributes:
      label: "🏷️ Type"
      options:
        - Refactor
        - Improvement
        - Change
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      placeholder: "Describe the task."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "📎 Additional information"
      placeholder: "Add more details, screenshots, or examples."
