<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<UseMonoGameNative>true</UseMonoGameNative>
		<MonoGameNativeTransitive>true</MonoGameNativeTransitive>
	</PropertyGroup>

	<Import Project="..\..\..\Sachssoft.Sasogine.Package.props" />

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows;net9.0-windows;net10.0-windows</TargetFrameworks>

		<MonoGamePlatform>Windows</MonoGamePlatform>

		<PackageId>Sachssoft.Sasogine.WindowsDX12</PackageId>
		<Title>Sasogine WindowsDX12</Title>
		<Description>
			Sasogine Windows backend based on MonoGame Native and DirectX 12.
		</Description>

		<PackageTags>
			MonoGame;Sasogine;Backend;Windows;DX12;DirectX12;GameEngine
		</PackageTags>

		<RootNamespace>Sachssoft.Engine.Backends.WindowsDX12</RootNamespace>

		<DefineConstants>
			$(DefineConstants);
			BACKEND_DX;
			BACKEND_DX12;
			DEVICE_DESKTOP
		</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference
			Include="MonoGame.Runtime.Windows.DX12"
			Version="$(MonoGameVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Basic\Sachssoft.Sasogine.csproj" />
	</ItemGroup>

</Project>