<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\Sachssoft.Sasogine.props" />

	<PropertyGroup>
		<PackageId>Sachssoft.Sasogine</PackageId>
		<Title>Sasogine</Title>

		<Description>
			Sasogine is a lightweight and flexible game engine framework based on MonoGame.
		</Description>

		<PackageTags>
			MonoGame;Sasogine;GameEngine;Framework;AOT;Trimming
		</PackageTags>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\..\CHANGELOG.md" Link="CHANGELOG.md" />
	</ItemGroup>

</Project>