using Microsoft.Xna.Framework;
using System.Collections.Generic;

namespace Sachssoft.Sasogine.Geometry
{
    /// <summary>
    /// Defines a backend for generating stroked geometry
    /// from polygon contours.
    /// </summary>
    public interface IPolygonStroker
    {
        /// <summary>
        /// Generates stroked polygon contours from the specified geometry.
        /// </summary>
        /// <param name="contours">
        /// The polygon contours to stroke.
        /// </param>
        /// <param name="options">
        /// The options that control stroke generation.
        /// </param>
        /// <returns>
        /// The polygon contours generated by the stroke operation.
        /// </returns>
        IReadOnlyList<IReadOnlyList<Vector2>> Stroke(
            IReadOnlyList<IReadOnlyList<Vector2>> contours,
            PolygonStrokeOptions options);
    }
}