using Microsoft.Xna.Framework;
using System.Collections.Generic;

namespace Sachssoft.Sasogine.Geometry
{
    /// <summary>
    /// Defines a backend for generating offset geometry
    /// from polygon contours.
    /// </summary>
    public interface IPolygonOffsetter
    {
        /// <summary>
        /// Generates offset contours from the specified polygon geometry.
        /// </summary>
        /// <param name="contours">
        /// The polygon contours to offset.
        /// </param>
        /// <param name="options">
        /// The options that control offset generation.
        /// </param>
        /// <returns>
        /// The polygon contours generated by the offset operation.
        /// </returns>
        IReadOnlyList<IReadOnlyList<Vector2>> Offset(
            IReadOnlyList<IReadOnlyList<Vector2>> contours,
            PolygonOffsetOptions options);
    }
}