using Microsoft.Xna.Framework;
using System.Collections.Generic;

namespace Sachssoft.Sasogine.Geometry
{
    /// <summary>
    /// Represents the result of a polygon triangulation operation.
    /// </summary>
    /// <remarks>
    /// The result contains the generated vertices and triangle indices.
    /// Each consecutive group of three indices defines one triangle.
    /// </remarks>
    public sealed class PolygonTriangulationResult
    {
        /// <summary>
        /// Gets the vertices generated by the triangulation.
        /// </summary>
        public IReadOnlyList<Vector2> Vertices { get; }

        /// <summary>
        /// Gets the indices defining the generated triangles.
        /// </summary>
        /// <remarks>
        /// Each consecutive group of three indices references vertices
        /// in <see cref="Vertices"/> and represents one triangle.
        /// </remarks>
        public IReadOnlyList<int> Indices { get; }

        /// <summary>
        /// Initializes a new instance of the
        /// <see cref="PolygonTriangulationResult"/> class.
        /// </summary>
        /// <param name="vertices">
        /// The vertices generated by the triangulation.
        /// </param>
        /// <param name="indices">
        /// The indices defining the generated triangles.
        /// </param>
        public PolygonTriangulationResult(
            IReadOnlyList<Vector2> vertices,
            IReadOnlyList<int> indices)
        {
            Vertices = vertices;
            Indices = indices;
        }
    }
}