using Sachssoft.Engine;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Sachssoft.Engine.Geometry;

/// <summary>
/// Represents a closed contour generated by a polygon tracing operation.
/// </summary>
public sealed class PolygonTraceContour
{
    private readonly ReadOnlyCollection<PolygonTraceSegment> _segments;

    /// <summary>
    /// Initializes a new instance of the <see cref="PolygonTraceContour"/> class.
    /// </summary>
    /// <param name="start">The start point of the closed contour.</param>
    /// <param name="segments">The segments that form the closed contour.</param>
    /// <param name="isHole">Whether the contour represents a hole.</param>
    /// <param name="sourceArea">
    /// The signed area of the source contour before simplification or curve fitting.
    /// </param>
    public PolygonTraceContour(
        Point2 start,
        IReadOnlyList<PolygonTraceSegment> segments,
        bool isHole,
        double sourceArea)
    {
        ArgumentNullException.ThrowIfNull(segments);

        if (!float.IsFinite(start.X) || !float.IsFinite(start.Y))
        {
            throw new ArgumentException(
                "The contour start point must contain finite coordinates.",
                nameof(start));
        }

        if (!double.IsFinite(sourceArea))
            throw new ArgumentOutOfRangeException(nameof(sourceArea));

        var copy = new PolygonTraceSegment[segments.Count];

        for (int i = 0; i < segments.Count; i++)
            copy[i] = segments[i];

        Start = start;
        _segments = Array.AsReadOnly(copy);
        IsHole = isHole;
        SourceArea = sourceArea;
    }

    /// <summary>Gets the start point of the contour.</summary>
    public Point2 Start { get; }

    /// <summary>Gets the traced segments that form the contour.</summary>
    public IReadOnlyList<PolygonTraceSegment> Segments => _segments;

    /// <summary>Gets whether the contour represents a hole.</summary>
    public bool IsHole { get; }

    /// <summary>
    /// Gets the signed area of the original traced pixel contour.
    /// </summary>
    /// <remarks>
    /// The sign reflects the contour winding while the absolute value represents
    /// the enclosed area in source-pixel units before simplification or curve fitting.
    /// </remarks>
    public double SourceArea { get; }
}
